# Generated by Django 4.2.6 on 2023-10-27 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='codigoqr',
            name='contenido',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=100),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
